package screens;

import classes.Apuesta;
import classes.Baraja;
import classes.Carta;
import classes.CasaDeApuestas;
import classes.JugadorRegistrado;
import classes.OrdenaCartas;
import classes.Premio;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class Mesa extends javax.swing.JFrame {

    /**
     * Creates new form Mesa
     */
    public Mesa() {
        this.b = new Baraja();
        initComponents();
        dinero.setValue(10);
        fase = 1;
        this.cartas = new JLabel[][]{{m1,m2,m3,m4,m5,m6,m7,m8,m9},{j1, j2, j3, j4,j5,j6,j7,j8,j9},{m11,m12,m13,m14,m15,m16,m17,m18,m19},{m21,m22,m23,m24,m25,m26,m27,m28,m29}};
        this.pesos = new JLabel[]{m10,j10,m20,m30};
        this.txtnombre = new JLabel[]{Crupier, Jugador, Jugador1, Jugador2};
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        salir = new javax.swing.JButton();
        txt = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        m1 = new javax.swing.JLabel();
        m2 = new javax.swing.JLabel();
        m3 = new javax.swing.JLabel();
        m4 = new javax.swing.JLabel();
        m5 = new javax.swing.JLabel();
        m6 = new javax.swing.JLabel();
        m7 = new javax.swing.JLabel();
        m8 = new javax.swing.JLabel();
        m9 = new javax.swing.JLabel();
        m10 = new javax.swing.JLabel();
        Crupier = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        mazo = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        j1 = new javax.swing.JLabel();
        j2 = new javax.swing.JLabel();
        j3 = new javax.swing.JLabel();
        j4 = new javax.swing.JLabel();
        j5 = new javax.swing.JLabel();
        j6 = new javax.swing.JLabel();
        j7 = new javax.swing.JLabel();
        j8 = new javax.swing.JLabel();
        j9 = new javax.swing.JLabel();
        j10 = new javax.swing.JLabel();
        Jugador = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        m11 = new javax.swing.JLabel();
        m12 = new javax.swing.JLabel();
        m13 = new javax.swing.JLabel();
        m14 = new javax.swing.JLabel();
        m15 = new javax.swing.JLabel();
        m16 = new javax.swing.JLabel();
        m17 = new javax.swing.JLabel();
        m18 = new javax.swing.JLabel();
        m19 = new javax.swing.JLabel();
        m20 = new javax.swing.JLabel();
        Jugador1 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        m21 = new javax.swing.JLabel();
        m22 = new javax.swing.JLabel();
        m23 = new javax.swing.JLabel();
        m24 = new javax.swing.JLabel();
        m25 = new javax.swing.JLabel();
        m26 = new javax.swing.JLabel();
        m27 = new javax.swing.JLabel();
        m28 = new javax.swing.JLabel();
        m29 = new javax.swing.JLabel();
        m30 = new javax.swing.JLabel();
        Jugador2 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        txtb = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        pasar = new javax.swing.JButton();
        apostar = new javax.swing.JButton();
        dinero = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel31 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        nombre = new javax.swing.JLabel();
        saldo = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Game");
        setIconImage(new ImageIcon(getClass().getResource("/imgages/Icono.png")).getImage() );
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel17.setBackground(new java.awt.Color(109, 131, 31));
        jPanel17.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 0), java.awt.Color.black));
        jPanel17.setForeground(new java.awt.Color(109, 131, 31));
        jPanel17.setLayout(new java.awt.CardLayout(20, 20));

        jPanel18.setBackground(new java.awt.Color(109, 131, 31));
        jPanel18.setLayout(new java.awt.GridBagLayout());

        jPanel19.setBackground(new java.awt.Color(109, 131, 31));
        jPanel19.setLayout(new java.awt.CardLayout());

        jPanel20.setBackground(new java.awt.Color(109, 131, 31));
        jPanel20.setLayout(new java.awt.GridBagLayout());

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgages/cruz.png"))); // NOI18N
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jPanel20.add(salir, new java.awt.GridBagConstraints());

        txt.setBackground(new java.awt.Color(0, 74, 0));
        txt.setFont(new java.awt.Font("Malayalam MN", 1, 36)); // NOI18N
        txt.setForeground(new java.awt.Color(223, 223, 223));
        txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt.setText("Comience el juego golpeando APOSTAR");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel20.add(txt, gridBagConstraints);

        jPanel19.add(jPanel20, "card2");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 12;
        jPanel18.add(jPanel19, gridBagConstraints);

        jPanel21.setBackground(new java.awt.Color(109, 131, 31));
        jPanel21.setLayout(new java.awt.GridBagLayout());

        jPanel22.setBackground(new java.awt.Color(109, 131, 31));
        jPanel22.setLayout(new java.awt.CardLayout());

        jPanel23.setBackground(new java.awt.Color(109, 131, 31));
        jPanel23.setLayout(new java.awt.GridBagLayout());

        jPanel24.setBackground(new java.awt.Color(109, 131, 31));
        jPanel24.setLayout(new java.awt.GridBagLayout());

        m1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgages/void.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel24.add(m1, gridBagConstraints);

        m2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgages/void.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel24.add(m2, gridBagConstraints);

        m3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgages/void.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel24.add(m3, gridBagConstraints);

        m4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgages/void.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel24.add(m4, gridBagConstraints);

        m5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgages/void.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel24.add(m5, gridBagConstraints);

        m6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgages/void.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel24.add(m6, gridBagConstraints);

        m7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgages/void.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel24.add(m7, gridBagConstraints);

        m8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgages/void.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel24.add(m8, gridBagConstraints);

        m9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgages/void.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel24.add(m9, gridBagConstraints);

        m10.setBackground(new java.awt.Color(0, 74, 0));
        m10.setFont(new java.awt.Font("Malayalam MN", 1, 48)); // NOI18N
        m10.setForeground(new java.awt.Color(223, 223, 223));
        m10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m10.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel24.add(m10, gridBagConstraints);

        Crupier.setFont(new java.awt.Font("Malayalam MN", 1, 24)); // NOI18N
        Crupier.setForeground(new java.awt.Color(51, 51, 51));
        Crupier.setText("CRUPIER");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        jPanel24.add(Crupier, gridBagConstraints);

        jPanel23.add(jPanel24, new java.awt.GridBagConstraints());

        jPanel1.setBackground(new java.awt.Color(109, 131, 31));
        jPanel1.setLayout(new java.awt.CardLayout(20, 20));

        mazo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mazo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgages/carta.jpg"))); // NOI18N
        mazo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mazoMouseClicked(evt);
            }
        });
        jPanel1.add(mazo, "card2");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        jPanel23.add(jPanel1, gridBagConstraints);

        jPanel25.setBackground(new java.awt.Color(109, 131, 31));
        jPanel25.setLayout(new java.awt.GridBagLayout());

        j1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgages/void.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel25.add(j1, gridBagConstraints);

        j2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgages/void.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel25.add(j2, gridBagConstraints);

        j3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgages/void.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel25.add(j3, gridBagConstraints);

        j4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgages/void.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel25.add(j4, gridBagConstraints);

        j5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgages/void.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel25.add(j5, gridBagConstraints);

        j6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgages/void.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel25.add(j6, gridBagConstraints);

        j7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgages/void.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel25.add(j7, gridBagConstraints);

        j8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgages/void.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel25.add(j8, gridBagConstraints);

        j9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgages/void.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel25.add(j9, gridBagConstraints);

        j10.setFont(new java.awt.Font("Malayalam MN", 1, 48)); // NOI18N
        j10.setForeground(new java.awt.Color(223, 223, 223));
        j10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j10.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel25.add(j10, gridBagConstraints);

        Jugador.setFont(new java.awt.Font("Malayalam MN", 1, 24)); // NOI18N
        Jugador.setForeground(new java.awt.Color(0, 102, 0));
        Jugador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        jPanel25.add(Jugador, gridBagConstraints);

        jPanel23.add(jPanel25, new java.awt.GridBagConstraints());

        jPanel26.setBackground(new java.awt.Color(109, 131, 31));
        jPanel26.setLayout(new java.awt.GridBagLayout());

        m11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgages/void.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel26.add(m11, gridBagConstraints);

        m12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgages/void.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel26.add(m12, gridBagConstraints);

        m13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgages/void.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel26.add(m13, gridBagConstraints);

        m14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgages/void.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel26.add(m14, gridBagConstraints);

        m15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgages/void.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel26.add(m15, gridBagConstraints);

        m16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgages/void.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel26.add(m16, gridBagConstraints);

        m17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgages/void.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel26.add(m17, gridBagConstraints);

        m18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgages/void.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel26.add(m18, gridBagConstraints);

        m19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgages/void.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel26.add(m19, gridBagConstraints);

        m20.setFont(new java.awt.Font("Malayalam MN", 1, 48)); // NOI18N
        m20.setForeground(new java.awt.Color(223, 223, 223));
        m20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m20.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel26.add(m20, gridBagConstraints);

        Jugador1.setFont(new java.awt.Font("Malayalam MN", 1, 24)); // NOI18N
        Jugador1.setForeground(new java.awt.Color(0, 102, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        jPanel26.add(Jugador1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel23.add(jPanel26, gridBagConstraints);

        jPanel27.setBackground(new java.awt.Color(109, 131, 31));
        jPanel27.setLayout(new java.awt.GridBagLayout());

        m21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgages/void.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel27.add(m21, gridBagConstraints);

        m22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgages/void.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel27.add(m22, gridBagConstraints);

        m23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgages/void.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel27.add(m23, gridBagConstraints);

        m24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgages/void.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel27.add(m24, gridBagConstraints);

        m25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgages/void.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel27.add(m25, gridBagConstraints);

        m26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgages/void.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel27.add(m26, gridBagConstraints);

        m27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgages/void.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel27.add(m27, gridBagConstraints);

        m28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgages/void.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel27.add(m28, gridBagConstraints);

        m29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgages/void.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel27.add(m29, gridBagConstraints);

        m30.setFont(new java.awt.Font("Malayalam MN", 1, 48)); // NOI18N
        m30.setForeground(new java.awt.Color(223, 223, 223));
        m30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m30.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel27.add(m30, gridBagConstraints);

        Jugador2.setFont(new java.awt.Font("Malayalam MN", 1, 24)); // NOI18N
        Jugador2.setForeground(new java.awt.Color(255, 102, 102));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        jPanel27.add(Jugador2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        jPanel23.add(jPanel27, gridBagConstraints);

        jPanel22.add(jPanel23, "card2");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 2.0;
        jPanel21.add(jPanel22, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.weightx = 0.6;
        gridBagConstraints.weighty = 0.1;
        jPanel18.add(jPanel21, gridBagConstraints);

        jPanel28.setBackground(new java.awt.Color(109, 131, 31));

        txtb.setBackground(new java.awt.Color(0, 71, 0));
        txtb.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        txtb.setForeground(new java.awt.Color(223, 223, 223));
        txtb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel28.add(txtb);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        jPanel18.add(jPanel28, gridBagConstraints);

        jPanel29.setBackground(new java.awt.Color(109, 131, 31));
        jPanel29.setLayout(new java.awt.CardLayout());

        jPanel30.setBackground(new java.awt.Color(109, 131, 31));
        jPanel30.setLayout(new java.awt.GridLayout(1, 0, 0, 7));

        pasar.setBackground(new java.awt.Color(153, 153, 0));
        pasar.setFont(new java.awt.Font("Malayalam MN", 1, 13)); // NOI18N
        pasar.setText("PASAR");
        pasar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasarActionPerformed(evt);
            }
        });
        jPanel30.add(pasar);

        apostar.setBackground(new java.awt.Color(51, 255, 0));
        apostar.setFont(new java.awt.Font("Malayalam MN", 1, 13)); // NOI18N
        apostar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgages/Apostar.png"))); // NOI18N
        apostar.setText("APOSTAR");
        apostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apostarActionPerformed(evt);
            }
        });
        jPanel30.add(apostar);

        dinero.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                dineroStateChanged(evt);
            }
        });
        jPanel30.add(dinero);

        jPanel2.setBackground(new java.awt.Color(109, 131, 31));
        jPanel2.setLayout(new java.awt.GridLayout(0, 1));

        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setText("11");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jPanel30.add(jPanel2);

        jPanel29.add(jPanel30, "card2");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 10;
        jPanel18.add(jPanel29, gridBagConstraints);

        jPanel31.setBackground(new java.awt.Color(109, 131, 31));
        jPanel31.setLayout(new java.awt.CardLayout());

        jPanel32.setBackground(new java.awt.Color(109, 131, 31));
        jPanel32.setLayout(new java.awt.GridBagLayout());

        nombre.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 2;
        jPanel32.add(nombre, gridBagConstraints);

        saldo.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 2;
        jPanel32.add(saldo, gridBagConstraints);

        jPanel33.setBackground(new java.awt.Color(102, 153, 0));
        jPanel33.setLayout(new java.awt.CardLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.1;
        jPanel32.add(jPanel33, gridBagConstraints);

        jPanel31.add(jPanel32, "card2");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        jPanel18.add(jPanel31, gridBagConstraints);

        jPanel17.add(jPanel18, "card2");

        getContentPane().add(jPanel17, "card3");

        setSize(new java.awt.Dimension(1500, 922));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private Baraja b = new Baraja();
    
    private final JLabel cartas[][];
    private final JLabel pesos[];
    private final JLabel txtnombre[];
    
    private boolean registrado;
    private int fase =0;
    
    private double apuesta=0;
    
    private static final JugadorRegistrado jugador [] = new JugadorRegistrado[3];
    
    private final ArrayList < Carta  > CartasJ1 = new ArrayList <>();
    private final ArrayList < Carta  > CartasJ2 = new ArrayList <>();
    private final ArrayList < Carta  > CartasJ3 = new ArrayList <>();
    private final ArrayList < Carta  > CartasM = new ArrayList <>();
    
    
    private int calculaPeso (ArrayList <Carta> cartas)
    {
        int acumula = 0;
        
        acumula = cartas.stream().map((carta) -> carta.getPeso()).reduce(acumula, Integer::sum); 
        
        return acumula;
    }
    
    public void setRegistrado(boolean registrado)
    {
        this.registrado=registrado;
    }
    
    public void setJugador (JugadorRegistrado jugador1, JugadorRegistrado jugador2,JugadorRegistrado jugador3)
    {
        Mesa.jugador[0]=jugador1;
        Mesa.jugador[1]=jugador2;
        Mesa.jugador[2]=jugador3;
        
        actualizarJugadores();    
    }
    
    private void actualizarJugadores()
    {
        for (int x =0; x < 3; x++)
        {
            txtnombre[x+1].setText(jugador[x].getNombre()+jugador[x].getApellidos()+" Saldo: "+jugador[x].getSaldo()+"$");
        }
    }
    
    private double saldoMaximo()
    {
        double maximo = jugador[0].getSaldo();
        for (int x =1;x<3;x++)
        {
            if (jugador[x].getSaldo()>maximo)
                maximo = jugador[x].getSaldo();
        }
        return maximo;
    }
    
    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        for (JugadorRegistrado jugador1 : jugador) {
            try (final PrintWriter salida = new PrintWriter(new BufferedWriter(new FileWriter("./src/RegistroJugadores/" + jugador1.getNIF() + ".txt", true)))) {
                DateTimeFormatter formatoCorto = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                salida.println("***************** SALIÓ DEL JUEGO*******************************\n");
                salida.println(LocalDate.now().format(formatoCorto));
                salida.println("*****************************************************************\n");
                salida.close();
            }catch (IOException ex) 
            {
                Warnning w = new Warnning();
                w.setTextoW("Error al crear archivo de registro");
                w.setVisible(true);
            }
            Dentro d = new Dentro();
            d.setVisible(true);
            this.setVisible(false);
            this.dispose();
        }
    }//GEN-LAST:event_salirActionPerformed

    private void pasarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasarActionPerformed
        if ((fase == 4)||(fase ==6))
        {
            String texto1;
            ArrayList <ArrayList <Carta>> cartas1= new ArrayList<>();
            cartas1.add(CartasM);
            cartas1.add(CartasJ1);
            String texto2;
            ArrayList <ArrayList <Carta>> cartas2= new ArrayList<>();
            cartas2.add(CartasM);
            cartas2.add(CartasJ2);
            String texto3;
            ArrayList <ArrayList <Carta>> cartas3= new ArrayList<>();
            cartas3.add(CartasM);
            cartas3.add(CartasJ3);
            
            Apuesta a1 = new Apuesta (cartas1,apuesta);
            Apuesta a2 = new Apuesta (cartas2,apuesta);
            Apuesta a3 = new Apuesta (cartas3,apuesta);
            
            if (a1.getPremio()==0)
            {
                jugador[0].aumentarSaldo(a1.verPremio());
                texto1=a1.getTexto();
                CasaDeApuestas.getregistrado("Crupier").premios.addPremio(new Premio(a1.verPremio(),true,a1.getPremio()));
                ((JugadorRegistrado)jugador[0]).premios.addPremio(new Premio(a1.verPremio(),true,a1.getPremio()));
                txtnombre[1].setText("Sin ganador");
            }
            else
            {
                if (a1.getGanador()==0)
                {
                    CasaDeApuestas.getregistrado("Crupier").aumentarSaldo(a1.verPremio());
                    jugador[0].retirarBeneficios(a1.verPremio());
                    texto1="Gana el Crupier con "+a1.getTexto();
                    txtnombre[1].setText(texto1);
                    CasaDeApuestas.getregistrado("Crupier").premios.addPremio(new Premio(a1.verPremio(),true,a1.getPremio()));
                }
                else 
                {
                    CasaDeApuestas.getregistrado("Crupier").retirarBeneficios(a1.verPremio());
                    jugador[0].aumentarSaldo(a1.verPremio());
                    texto1="Gana "+jugador[0].getNIF()+" con "+a1.getTexto();
                    txtnombre[1].setText(texto1);
                    ((JugadorRegistrado)jugador[0]).premios.addPremio(new Premio(a1.verPremio(),true,a1.getPremio()));
                }
            }
            
            try (PrintWriter salida = new PrintWriter(new BufferedWriter(new FileWriter("./src/RegistroJugadores/"+jugador[0].getNIF()+".txt",true)))) 
            {
                DateTimeFormatter formatoCorto = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                salida.println("--------------- Resultados de la partida --------------------------\n");  
                salida.println(LocalDate.now().format(formatoCorto));
                salida.println("Dinero en Juego: "+ apuesta);
                salida.println("Cartas del jugador: ");
                for (int x =0; x<CartasJ1.size(); x++)
                {
                    salida.println("\t"+CartasJ1.get(x).toString());
                }
                salida.println("Cartas del crupier: ");
                for (int x =0; x<CartasM.size(); x++)
                {
                    salida.println("\t"+CartasM.get(x).toString());
                }
                
                salida.println(texto1);
                salida.println("Ganancia: "+a1.verPremio());
                salida.println("Nuevo saldo: "+jugador[0].getSaldo());
                salida.println("--------------------------------------------------------------\n");  
                salida.close();
                
                salida.close();
            } 
            catch (IOException ex) 
            {
                Warnning w = new Warnning();
                w.setTextoW("Error al crear archivo de registro");
                w.setVisible(true);
            }
            
            
            if (a2.getPremio()==0)
            {
                jugador[1].aumentarSaldo(a2.verPremio());
                texto2=a2.getTexto();
                CasaDeApuestas.getregistrado("Crupier").premios.addPremio(new Premio(a2.verPremio(),true,a2.getPremio()));
                ((JugadorRegistrado)jugador[1]).premios.addPremio(new Premio(a2.verPremio(),true,a2.getPremio()));
                txtnombre[2].setText("Sin ganador");
            }
            else
            {
                if (a2.getGanador()==0)
                {
                    CasaDeApuestas.getregistrado("Crupier").aumentarSaldo(a2.verPremio());
                    jugador[1].retirarBeneficios(a2.verPremio());
                    texto2="Gana el Crupier con "+a2.getTexto();
                    txtnombre[2].setText(texto2);
                    CasaDeApuestas.getregistrado("Crupier").premios.addPremio(new Premio(a2.verPremio(),true,a2.getPremio()));
                }
                else 
                {
                    CasaDeApuestas.getregistrado("Crupier").retirarBeneficios(a2.verPremio());
                    jugador[1].aumentarSaldo(a2.verPremio());
                    texto2="Gana "+jugador[1].getNIF()+" con "+a2.getTexto();
                    txtnombre[2].setText(texto2);
                    ((JugadorRegistrado)jugador[1]).premios.addPremio(new Premio(a2.verPremio(),true,a2.getPremio()));
                }
            }
            
            try (PrintWriter salida = new PrintWriter(new BufferedWriter(new FileWriter("./src/RegistroJugadores/"+jugador[1].getNIF()+".txt",true)))) 
            {
                DateTimeFormatter formatoCorto = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                salida.println("--------------- Resultados de la partida --------------------------\n");  
                salida.println(LocalDate.now().format(formatoCorto));
                salida.println("Dinero en Juego: "+ apuesta);
                salida.println("Cartas del jugador: ");
                for (int x =0; x<CartasJ2.size(); x++)
                {
                    salida.println("\t"+CartasJ2.get(x).toString());
                }
                salida.println("Cartas del crupier: ");
                for (int x =0; x<CartasM.size(); x++)
                {
                    salida.println("\t"+CartasM.get(x).toString());
                }
                
                salida.println(texto2);
                salida.println("Ganancia: "+a2.verPremio());
                salida.println("Nuevo saldo: "+jugador[1].getSaldo());
                salida.println("--------------------------------------------------------------\n");  
                salida.close();
                
                salida.close();
            } 
            catch (IOException ex) 
            {
                Warnning w = new Warnning();
                w.setTextoW("Error al crear archivo de registro");
                w.setVisible(true);
            }
            
            
            
            if (a3.getPremio()==0)
            {
                jugador[0].aumentarSaldo(a3.verPremio());
                texto3=a3.getTexto();
                CasaDeApuestas.getregistrado("Crupier").premios.addPremio(new Premio(a3.verPremio(),true,a3.getPremio()));
                ((JugadorRegistrado)jugador[2]).premios.addPremio(new Premio(a3.verPremio(),true,a3.getPremio()));
                txtnombre[3].setText("Sin ganador");
            }
            else
            {
                if (a3.getGanador()==0)
                {
                    CasaDeApuestas.getregistrado("Crupier").aumentarSaldo(a3.verPremio());
                    jugador[2].retirarBeneficios(a3.verPremio());
                    texto3="Gana el Crupier con "+a3.getTexto();
                    txtnombre[3].setText(texto3);
                    CasaDeApuestas.getregistrado("Crupier").premios.addPremio(new Premio(a3.verPremio(),true,a3.getPremio()));
                }
                else 
                {
                    CasaDeApuestas.getregistrado("Crupier").retirarBeneficios(a3.verPremio());
                    jugador[2].aumentarSaldo(a3.verPremio());
                    texto3="Gana "+jugador[2].getNIF()+" con "+a3.getTexto();
                    txtnombre[3].setText(texto3);
                    ((JugadorRegistrado)jugador[2]).premios.addPremio(new Premio(a3.verPremio(),true,a3.getPremio()));
                }
            }
            
            try (PrintWriter salida = new PrintWriter(new BufferedWriter(new FileWriter("./src/RegistroJugadores/"+jugador[2].getNIF()+".txt",true)))) 
            {
                DateTimeFormatter formatoCorto = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                salida.println("--------------- Resultados de la partida --------------------------\n");  
                salida.println(LocalDate.now().format(formatoCorto));
                salida.println("Dinero en Juego: "+ apuesta);
                salida.println("Cartas del jugador: ");
                for (int x =0; x<CartasJ3.size(); x++)
                {
                    salida.println("\t"+CartasJ3.get(x).toString());
                }
                salida.println("Cartas del crupier: ");
                for (int x =0; x<CartasM.size(); x++)
                {
                    salida.println("\t"+CartasM.get(x).toString());
                }
                
                salida.println(texto1);
                salida.println("Ganancia: "+a3.verPremio());
                salida.println("Nuevo saldo: "+jugador[2].getSaldo());
                salida.println("--------------------------------------------------------------\n");  
                salida.close();
                
                salida.close();
            } 
            catch (IOException ex) 
            {
                Warnning w = new Warnning();
                w.setTextoW("Error al crear archivo de registro");
                w.setVisible(true);
            }
            
            
            
            
            
            
            //Muestra las Cartas  
            for (int x =0;x < CartasM.size(); x++)
            {
                this.cartas[0][x].setIcon(CartasM.get(x).getImagen());
            }
            pesos[0].setText(calculaPeso(CartasM)+"");
            
            txt.setText("Golpee APOSTAR para vaciar la mesa");
            txtb.setText("");
            fase = 9;
        }
    }//GEN-LAST:event_pasarActionPerformed

    private void apostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apostarActionPerformed
        if (fase == 3)
        {
            if (Double.parseDouble(dinero.getValue().toString())<10)
            {
                dinero.setValue(10);
                Warnning w = new Warnning();
                w.setTextoW("La apuesta minima son 10$");
                w.setVisible(true);
            }
            else if (Double.parseDouble(dinero.getValue().toString())>saldoMaximo())
            {
                dinero.setValue(saldoMaximo());
                Warnning w = new Warnning();
                w.setTextoW("No puede apostar tanto");
                w.setVisible(true);
            }
            else 
            {
                apuesta = Double.parseDouble(dinero.getValue().toString());
                fase = 4;
                dinero.setValue(10);
                txt.setText("Golpee el mazo para obtener más cartas o PASAR para ver el resultado");
                for (int x =0; x< 3;x++)
                {
                    jugador[x].retirarBeneficios(apuesta);
                
                    
                    try (PrintWriter salida = new PrintWriter(new BufferedWriter(new FileWriter("./src/RegistroJugadores/"+jugador[x].getNIF()+".txt",true)))) 
                    {
                        DateTimeFormatter formatoCorto = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                        salida.println("--------------- Apuesta realizada --------------------------\n");  
                        salida.println(LocalDate.now().format(formatoCorto));
                        salida.println("En juego: "+apuesta);
                        salida.println("Nuevo saldo: "+jugador[x].getSaldo());
                        salida.println("-----------------------------------------------------------\n");
                        salida.close();
                    } 
                    catch (IOException ex) 
                    {
                        Warnning w = new Warnning();
                        w.setTextoW("Error al crear archivo de registro");
                        w.setVisible(true);
                    }
                }
                actualizarJugadores();
                
            }
        } 
        if (fase ==1)
        {
            actualizarJugadores();
            CasaDeApuestas.getregistrado("Crupier").añadirPartida();  
            for (JugadorRegistrado jugador1 : jugador) {
                ((JugadorRegistrado) jugador1).añadirPartida();
                try (final PrintWriter salida = new PrintWriter(new BufferedWriter(new FileWriter("./src/RegistroJugadores/" + jugador1.getNIF() + ".txt", true)))) {
                    DateTimeFormatter formatoCorto = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                    salida.println("******************* Juego Nuevo ***************************\n");
                    salida.println(LocalDate.now().format(formatoCorto));
                    salida.close();
                }catch (IOException ex) 
                {
                    Warnning w = new Warnning();
                    w.setTextoW("Error al crear archivo de registro");
                    w.setVisible(true);
                }
            }
            //Reparte las cartas
            CartasJ1.addAll(b.darCartas(2));
            CartasJ2.addAll(b.darCartas(2));
            CartasJ3.addAll(b.darCartas(2));
            CartasM.addAll(b.darCartas(2));
            //Ordena las cartas
            CartasJ1.sort(new OrdenaCartas());
            CartasJ2.sort(new OrdenaCartas());
            CartasJ3.sort(new OrdenaCartas());
            CartasM.sort(new OrdenaCartas());
            //Muestra las Cartas  
            for (int y =0;y < CartasJ3.size(); y++)
            {
                cartas[3][y].setIcon(CartasJ3.get(y).getImagen());
            }
            for (int y =0;y < CartasJ2.size(); y++)
            {
                cartas[2][y].setIcon(CartasJ2.get(y).getImagen());
            }
            for (int y =0;y < CartasJ1.size(); y++)
            {
                cartas[1][y].setIcon(CartasJ1.get(y).getImagen());
            }
            //Calcula los pesos de los ases
            int contador =0;
            for (int y =0;y < CartasJ3.size(); y++)
            {
                if (CartasJ3.get(y).getPeso()==0)
                    contador ++;
            }
            if (contador > 0)
            {
                txtb.setText("Elija el valor de su as 1 u 11");
                fase = 2;
            }
            else 
            {
                txt.setText("Realice su apuesta");
                fase = 3;
                cartas[0][0].setIcon(CartasM.get(0).getImagen());
            }
            for (int y =0;y < CartasM.size(); y++)
            {
                if (CartasM.get(y).getPeso()==0)
                {
                    if ((calculaPeso(CartasM)+11)<22)
                        CartasM.get(y).setPeso(11);
                    else
                        CartasM.get(y).setPeso(1);                        
                }
            }
            for (int y =0;y < CartasJ1.size(); y++)
            {
                if (CartasJ1.get(y).getPeso()==0)
                {
                    if ((calculaPeso(CartasJ1)+11)<22)
                        CartasJ1.get(y).setPeso(11);
                    else
                        CartasJ1.get(y).setPeso(1);                        
                }
            }
            for (int y =0;y < CartasJ2.size(); y++)
            {
                if (CartasJ2.get(y).getPeso()==0)
                {
                    if ((calculaPeso(CartasJ2)+11)<22)
                        CartasJ2.get(y).setPeso(11);
                    else
                        CartasJ2.get(y).setPeso(1);                        
                }
            }
            //Calcula los pesos totales
            pesos[0].setText("X");
            pesos[1].setText(calculaPeso(CartasJ1)+"");
            pesos[2].setText(calculaPeso(CartasJ2)+"");
            pesos[3].setText(calculaPeso(CartasJ3)+"");
        }
        if (fase == 9)
        {
            actualizarJugadores();
            //Vacia las cartas
            ImageIcon vacio = new ImageIcon("./src/imgages/void.png");
            for (int x =0;x < cartas[0].length; x++)
            {
                this.cartas[1][x].setIcon(vacio);
                this.cartas[0][x].setIcon(vacio);
                this.cartas[2][x].setIcon(vacio);
                this.cartas[3][x].setIcon(vacio);
            } 
            txt.setText("Comiece el juego golpeando APOSTAR");
            fase = 1;
            CartasM.clear();
            CartasJ1.clear();
            CartasJ2.clear();
            CartasJ3.clear();
            pesos[0].setText("0");
            pesos[1].setText("0");
            pesos[2].setText("0");
            pesos[3].setText("0");
        }

    }//GEN-LAST:event_apostarActionPerformed

    private void dineroStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_dineroStateChanged
      if (fase == 3)
        {
            if (Double.parseDouble(dinero.getValue().toString())<10)
            {
                dinero.setValue(10);
                Warnning w = new Warnning();
                w.setTextoW("La apuesta minima son 10$");
                w.setVisible(true);
            }
            else if (Double.parseDouble(dinero.getValue().toString())>saldoMaximo())
            {
                dinero.setValue(saldoMaximo());
                Warnning w = new Warnning();
                w.setTextoW("No puede apostar tanto");
                w.setVisible(true);
            }
        }  
    }//GEN-LAST:event_dineroStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (fase == 2)
        {
            boolean control = true;
            int contador = 0;
            for (int x = 0; x < CartasJ3.size(); x++)
            {
                if (control &&(CartasJ3.get(x).getPeso()==0))
                {
                    control = false;
                    CartasJ3.get(x).setPeso(1);
                }
            }

            for (int x = 0; x < CartasJ3.size(); x++)
            {
                if (CartasJ3.get(x).getPeso()==0)
                    contador++;
            }    
            
            if (contador == 0)
            {
                fase = 3;  
                txt.setText("Realice su apuesta");
                txtb.setText("");
                pesos[3].setText(calculaPeso(CartasJ3)+"");
                cartas[0][0].setIcon(CartasM.get(0).getImagen());
            }
        }
        if (fase == 5)
        {
            boolean control = true;
            int contador = 0;
            for (int x = 0; x < CartasJ3.size(); x++)
            {
                if (control &&(CartasJ3.get(x).getPeso()==0))
                {
                    control = false;
                    CartasJ3.get(x).setPeso(1);
                }
            }

            for (int x = 0; x < CartasJ3.size(); x++)
            {
                if (CartasJ3.get(x).getPeso()==0)
                    contador++;
            }    
            
            if (contador == 0)
            {
                fase = 4;  
                txtb.setText("");
                pesos[3].setText(calculaPeso(CartasJ3)+"");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (fase == 5)
        {
            boolean control = true;
            int contador = 0;
            for (int x = 0; x < CartasJ3.size(); x++)
            {
                if (control &&(CartasJ3.get(x).getPeso()==0))
                {
                    control = false;
                    CartasJ3.get(x).setPeso(11);
                }
            }

            for (int x = 0; x < CartasJ3.size(); x++)
            {
                if (CartasJ3.get(x).getPeso()==0)
                    contador++;
            }    
            
            if (contador == 0)
            {
                fase = 4;  
                txtb.setText("");
                pesos[3].setText(calculaPeso(CartasJ3)+"");
            }
        }
        if (fase == 2)
        {
            boolean control = true;
            int contador = 0;
            for (int x = 0; x < CartasJ3.size(); x++)
            {
                if (control &&(CartasJ3.get(x).getPeso()==0))
                {
                    control = false;
                    CartasJ3.get(x).setPeso(11);
                }
            }

            for (int x = 0; x < CartasJ3.size(); x++)
            {
                if (CartasJ3.get(x).getPeso()==0)
                    contador++;
            }    
            if (contador == 0)
            {
                fase = 3;  
                txt.setText("Realice su apuesta");
                txtb.setText("");
                pesos[3].setText(calculaPeso(CartasJ3)+"");
                cartas[0][0].setIcon(CartasM.get(0).getImagen());
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void mazoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mazoMouseClicked
        if (fase == 4)
        {
            //Reparte las cartas
            CartasJ3.addAll(b.darCartas(1));
            if (calculaPeso(CartasM) < 17)
            {
               CartasM.addAll(b.darCartas(1)); 
            }
            if (calculaPeso(CartasJ1) < 17)
            {
               CartasJ1.addAll(b.darCartas(1)); 
            }
            if (calculaPeso(CartasJ2) < 17)
            {
               CartasJ2.addAll(b.darCartas(1)); 
            }
            //Ordena las cartas
            CartasJ3.sort(new OrdenaCartas());
            CartasM.sort(new OrdenaCartas());
            CartasJ1.sort(new OrdenaCartas());
            CartasJ2.sort(new OrdenaCartas());
            //Muestra las Cartas  
            for (int y =0;y < CartasJ3.size(); y++)
            {
                cartas[3][y].setIcon(CartasJ3.get(y).getImagen());
            }
            for (int y =0;y < CartasJ2.size(); y++)
            {
                cartas[2][y].setIcon(CartasJ2.get(y).getImagen());
            }
            for (int y =0;y < CartasJ1.size(); y++)
            {
                cartas[1][y].setIcon(CartasJ1.get(y).getImagen());
            }
            //Calcula los pesos de los ases
            int contador =0;
            for (int y =0;y < CartasJ3.size(); y++)
            {
                if (CartasJ3.get(y).getPeso()==0)
                    contador ++;
            }
            if (contador > 0)
            {
                txtb.setText("Elija el valor de su as 1 u 11");
                fase = 5;
            }

            for (int y =0;y < CartasM.size(); y++)
            {
                if (CartasM.get(y).getPeso()==0)
                {
                    if ((calculaPeso(CartasM)+11)<22)
                        CartasM.get(y).setPeso(11);
                    else
                        CartasM.get(y).setPeso(1);                        
                }
            }
            for (int y =0;y < CartasJ2.size(); y++)
            {
                if (CartasJ2.get(y).getPeso()==0)
                {
                    if ((calculaPeso(CartasJ2)+11)<22)
                        CartasJ2.get(y).setPeso(11);
                    else
                        CartasJ2.get(y).setPeso(1);                        
                }
            }
            for (int y =0;y < CartasJ1.size(); y++)
            {
                if (CartasJ1.get(y).getPeso()==0)
                {
                    if ((calculaPeso(CartasJ1)+11)<22)
                        CartasJ1.get(y).setPeso(11);
                    else
                        CartasJ1.get(y).setPeso(1);                        
                }
            }
            //Calcula los pesos totales
            pesos[0].setText("X");
            pesos[1].setText(calculaPeso(CartasJ1)+"");
            pesos[2].setText(calculaPeso(CartasJ2)+"");
            pesos[3].setText(calculaPeso(CartasJ3)+"");
            
            if (CartasJ3.size()==9)
            {
                txt.setText("No puede recibir más cartas pulse PASAR");
                fase = 6;
            }
        }
    }//GEN-LAST:event_mazoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Game().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Crupier;
    private javax.swing.JLabel Jugador;
    private javax.swing.JLabel Jugador1;
    private javax.swing.JLabel Jugador2;
    private javax.swing.JButton apostar;
    private javax.swing.JSpinner dinero;
    private javax.swing.JLabel j1;
    private javax.swing.JLabel j10;
    private javax.swing.JLabel j2;
    private javax.swing.JLabel j3;
    private javax.swing.JLabel j4;
    private javax.swing.JLabel j5;
    private javax.swing.JLabel j6;
    private javax.swing.JLabel j7;
    private javax.swing.JLabel j8;
    private javax.swing.JLabel j9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JLabel m1;
    private javax.swing.JLabel m10;
    private javax.swing.JLabel m11;
    private javax.swing.JLabel m12;
    private javax.swing.JLabel m13;
    private javax.swing.JLabel m14;
    private javax.swing.JLabel m15;
    private javax.swing.JLabel m16;
    private javax.swing.JLabel m17;
    private javax.swing.JLabel m18;
    private javax.swing.JLabel m19;
    private javax.swing.JLabel m2;
    private javax.swing.JLabel m20;
    private javax.swing.JLabel m21;
    private javax.swing.JLabel m22;
    private javax.swing.JLabel m23;
    private javax.swing.JLabel m24;
    private javax.swing.JLabel m25;
    private javax.swing.JLabel m26;
    private javax.swing.JLabel m27;
    private javax.swing.JLabel m28;
    private javax.swing.JLabel m29;
    private javax.swing.JLabel m3;
    private javax.swing.JLabel m30;
    private javax.swing.JLabel m4;
    private javax.swing.JLabel m5;
    private javax.swing.JLabel m6;
    private javax.swing.JLabel m7;
    private javax.swing.JLabel m8;
    private javax.swing.JLabel m9;
    private javax.swing.JLabel mazo;
    private javax.swing.JLabel nombre;
    private javax.swing.JButton pasar;
    private javax.swing.JLabel saldo;
    private javax.swing.JButton salir;
    private javax.swing.JLabel txt;
    private javax.swing.JLabel txtb;
    // End of variables declaration//GEN-END:variables
}
