/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens;

import classes.CasaDeApuestas;
import classes.Premio;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author mr.blissfulgrin
 */
public class Ver extends javax.swing.JFrame {

    /**
     * Creates new form Ver
     */
    public Ver() {
        initComponents();
        
        actualizarList();
        
        //Muestra La Contabilidad General
        try
        {
            CasaDeApuestas.generarRegistro();
            String cadena;
            FileReader f = new FileReader("./src/RegistroMaster/Registro.txt");
            try (BufferedReader b = new BufferedReader(f)) 
            {
                while((cadena = b.readLine())!=null) 
                {
                    txt1.setText(txt1.getText()+"\n"+cadena);
                }
            }
            
        }
        catch(IOException e)
        {
            Warnning w = new Warnning();
            w.setTextoW("Error al leer archivo de registro");
            w.setVisible(true);
        }
        
        //Recoge los archivos de la Contabilidad asociada a cada jugador
        String listado[]= new File("./src/RegistroJugadores").list();
        
        for (int x=0; x<listado.length;x++)
        {
            if(listado[x].charAt(0)=='.')
                listado[x]="";
        }
        
        List.setListData(listado);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        volver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tab = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt1 = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jTab = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        L1 = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        txt3 = new javax.swing.JTextArea();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        L2 = new javax.swing.JList<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        txt0 = new javax.swing.JTextArea();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        L3 = new javax.swing.JList<>();
        jScrollPane10 = new javax.swing.JScrollPane();
        txt4 = new javax.swing.JTextArea();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        L4 = new javax.swing.JList<>();
        jScrollPane12 = new javax.swing.JScrollPane();
        txt5 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt2 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        List = new javax.swing.JList<>();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane13 = new javax.swing.JScrollPane();
        L5 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt6 = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Registro de Jugadores");
        setIconImage(new ImageIcon(getClass().getResource("/imgages/Icono.png")).getImage() );
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgages/Flecha.jpg"))); // NOI18N
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        jPanel4.add(volver, new java.awt.GridBagConstraints());

        jLabel1.setFont(new java.awt.Font("Malayalam MN", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de Jugadores  ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel4.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(jPanel4, gridBagConstraints);

        tab.setBackground(new java.awt.Color(204, 255, 204));

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));
        jPanel5.setLayout(new java.awt.CardLayout());

        txt1.setEditable(false);
        txt1.setColumns(20);
        txt1.setRows(5);
        txt1.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jScrollPane1.setViewportView(txt1);

        jPanel5.add(jScrollPane1, "card2");

        tab.addTab("Listado", jPanel5);

        jPanel6.setLayout(new java.awt.CardLayout());

        jPanel8.setBackground(new java.awt.Color(204, 255, 204));
        jPanel8.setLayout(new java.awt.CardLayout());

        jPanel9.setBackground(new java.awt.Color(204, 255, 204));
        jPanel9.setLayout(new java.awt.GridBagLayout());

        L1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Pareja", "DoblePareja", "Trío", "Color", "Full", "Poker", "Total" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        L1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        L1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                L1ValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(L1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel9.add(jScrollPane5, gridBagConstraints);

        txt3.setEditable(false);
        txt3.setColumns(20);
        txt3.setRows(5);
        jScrollPane6.setViewportView(txt3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.1;
        jPanel9.add(jScrollPane6, gridBagConstraints);

        jTab.addTab("VecesPremio", jPanel9);

        jPanel13.setBackground(new java.awt.Color(204, 255, 204));
        jPanel13.setLayout(new java.awt.GridBagLayout());

        L2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Pareja", "DoblePareja", "Trío", "Color", "Full", "Poker" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        L2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        L2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                L2ValueChanged(evt);
            }
        });
        jScrollPane7.setViewportView(L2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel13.add(jScrollPane7, gridBagConstraints);

        txt0.setEditable(false);
        txt0.setColumns(20);
        txt0.setRows(5);
        jScrollPane8.setViewportView(txt0);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.1;
        jPanel13.add(jScrollPane8, gridBagConstraints);

        jTab.addTab("JugadoresPremio", jPanel13);

        jPanel14.setBackground(new java.awt.Color(204, 255, 204));
        jPanel14.setLayout(new java.awt.GridBagLayout());

        L3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        L3.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                L3ValueChanged(evt);
            }
        });
        jScrollPane9.setViewportView(L3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.1;
        jPanel14.add(jScrollPane9, gridBagConstraints);

        txt4.setEditable(false);
        txt4.setColumns(20);
        txt4.setRows(5);
        jScrollPane10.setViewportView(txt4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        jPanel14.add(jScrollPane10, gridBagConstraints);

        jTab.addTab("PremiosDeJugador", jPanel14);

        jPanel15.setBackground(new java.awt.Color(204, 255, 204));
        jPanel15.setLayout(new java.awt.GridBagLayout());

        L4.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        L4.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                L4ValueChanged(evt);
            }
        });
        jScrollPane11.setViewportView(L4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.1;
        jPanel15.add(jScrollPane11, gridBagConstraints);

        txt5.setEditable(false);
        txt5.setColumns(20);
        txt5.setRows(5);
        jScrollPane12.setViewportView(txt5);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.1;
        gridBagConstraints.weighty = 0.1;
        jPanel15.add(jScrollPane12, gridBagConstraints);

        jTab.addTab("VecesPremiosDeJugador", jPanel15);

        jPanel8.add(jTab, "card2");

        jPanel6.add(jPanel8, "card2");

        tab.addTab("Premios", jPanel6);

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setLayout(new java.awt.CardLayout());

        jPanel10.setLayout(new java.awt.GridBagLayout());

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setToolTipText("");

        txt2.setEditable(false);
        txt2.setColumns(20);
        txt2.setRows(5);
        jScrollPane4.setViewportView(txt2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.2;
        gridBagConstraints.weighty = 0.2;
        jPanel10.add(jScrollPane4, gridBagConstraints);

        List.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        List.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        List.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(List);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.1;
        jPanel10.add(jScrollPane2, gridBagConstraints);

        jTabbedPane1.addTab("tab3", jPanel10);

        jPanel11.setLayout(new java.awt.GridBagLayout());

        L5.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                L5ValueChanged(evt);
            }
        });
        jScrollPane13.setViewportView(L5);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel11.add(jScrollPane13, gridBagConstraints);

        txt6.setEditable(false);
        txt6.setColumns(20);
        txt6.setRows(5);
        jScrollPane3.setViewportView(txt6);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.1;
        jPanel11.add(jScrollPane3, gridBagConstraints);

        jTabbedPane1.addTab("tab3", jPanel11);

        jPanel3.add(jTabbedPane1, "card2");

        tab.addTab("Jugadores", jPanel3);

        tab.setSelectedIndex(0);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel1.add(tab, gridBagConstraints);
        tab.getAccessibleContext().setAccessibleName("tab");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 2.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel7.setBackground(new java.awt.Color(0, 51, 51));
        jPanel7.setLayout(new java.awt.CardLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgages/POKER.jpg"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(471, 100));
        jPanel7.add(jLabel2, "card2");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        getContentPane().add(jPanel7, gridBagConstraints);

        setSize(new java.awt.Dimension(700, 672));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Abre el JFrame Dentro
     */
    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        Admin d = new Admin();
        d.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_volverActionPerformed

    /**
     * Muestra la contabilidad de un jugador en concreto
     */
    private void ListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListValueChanged
        try
        {
            txt2.setText("");
            String cadena;
            FileReader f = new FileReader("./src/RegistroJugadores/"+List.getSelectedValue());
            try (BufferedReader b = new BufferedReader(f)) 
            {
                while((cadena = b.readLine())!=null) 
                {
                    txt2.setText(txt2.getText()+"\n"+cadena);
                }
            }
            
        }
        catch(IOException e)
        {
            Warnning w = new Warnning();
            w.setTextoW("Error al leer archivo de registro");
            w.setVisible(true);
        }
    }//GEN-LAST:event_ListValueChanged

    private void L1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_L1ValueChanged
        int pareja = 0;
        int parejaMesa = 0;
        int doblePareja = 0;
        int dobleParejaMesa = 0;
        int trio = 0;
        int trioMesa = 0;
        int full = 0;
        int fullMesa = 0;
        int color = 0;
        int colorMesa = 0;
        int poker = 0;
        int pokerMesa = 0;
        Object [] datos = CasaDeApuestas.getRegistro().keySet().toArray();
        String [] claves = new String[datos.length];
        for (int x =0; x < datos.length; x++)
            claves[x] = datos [x].toString();
        for (String clave : claves) {
            pareja+=CasaDeApuestas.getregistrado(clave).premios.getPareja();
            parejaMesa+=CasaDeApuestas.getregistrado(clave).premios.getParejaMesa();
            doblePareja+=CasaDeApuestas.getregistrado(clave).premios.getDoblePareja();
            dobleParejaMesa+=CasaDeApuestas.getregistrado(clave).premios.getDobleParejaMesa();
            trio+=CasaDeApuestas.getregistrado(clave).premios.getTrio();
            trioMesa+=CasaDeApuestas.getregistrado(clave).premios.getTrioMesa();
            full+=CasaDeApuestas.getregistrado(clave).premios.getFull();
            fullMesa+=CasaDeApuestas.getregistrado(clave).premios.getFullMesa();
            color+=CasaDeApuestas.getregistrado(clave).premios.getColor();
            colorMesa+=CasaDeApuestas.getregistrado(clave).premios.getColorMesa();
            poker+=CasaDeApuestas.getregistrado(clave).premios.getPoker();
            pokerMesa+=CasaDeApuestas.getregistrado(clave).premios.getPokerMesa();
        }
        switch(L1.getSelectedIndex())
        {
            case 0:
                txt3.setText("Parejas:\n");
                txt3.setText(txt3.getText()+"\tEn juego simple: "+ pareja+"\n");
                txt3.setText(txt3.getText()+"\tEn mesa: "+ parejaMesa+"\n");
                txt3.setText(txt3.getText()+"\tTotal: "+ (pareja+parejaMesa)+"\n");
                break;
            case 1:
                txt3.setText("DoblesParejas:\n");
                txt3.setText(txt3.getText()+"\tEn juego simple: "+ doblePareja+"\n");
                txt3.setText(txt3.getText()+"\tEn mesa: "+ dobleParejaMesa+"\n");
                txt3.setText(txt3.getText()+"\tTotal: "+ (doblePareja+dobleParejaMesa)+"\n");
                break;
            case 2:
                txt3.setText("Trios:\n");
                txt3.setText(txt3.getText()+"\tEn juego simple: "+ trio+"\n");
                txt3.setText(txt3.getText()+"\tEn mesa: "+ trioMesa+"\n");
                txt3.setText(txt3.getText()+"\tTotal: "+ (trio+trioMesa)+"\n");
                break;
            case 3:
                txt3.setText("Color:\n");
                txt3.setText(txt3.getText()+"\tEn juego simple: "+ color+"\n");
                txt3.setText(txt3.getText()+"\tEn mesa: "+ colorMesa+"\n");
                txt3.setText(txt3.getText()+"\tTotal: "+ (color+colorMesa)+"\n");
                break;
            case 4:
                txt3.setText("Full:\n");
                txt3.setText(txt3.getText()+"\tEn juego simple: "+ full+"\n");
                txt3.setText(txt3.getText()+"\tEn mesa: "+ fullMesa+"\n");
                txt3.setText(txt3.getText()+"\tTotal: "+ (full+fullMesa)+"\n");
                break;
            case 5:
                txt3.setText("Poker:\n");
                txt3.setText(txt3.getText()+"\tEn juego simple: "+ poker+"\n");
                txt3.setText(txt3.getText()+"\tEn mesa: "+ pokerMesa+"\n");
                txt3.setText(txt3.getText()+"\tTotal: "+ (poker+pokerMesa)+"\n");
                break;
            case 6:
                txt3.setText("Parejas:\n");
                txt3.setText(txt3.getText()+"\tEn juego simple: "+ pareja+"\n");
                txt3.setText(txt3.getText()+"\tEn mesa: "+ parejaMesa+"\n");
                txt3.setText(txt3.getText()+"\tTotal: "+ (pareja+parejaMesa)+"\n");
                txt3.setText(txt3.getText()+"DoblesParejas:\n");
                txt3.setText(txt3.getText()+"\tEn juego simple: "+ doblePareja+"\n");
                txt3.setText(txt3.getText()+"\tEn mesa: "+ dobleParejaMesa+"\n");
                txt3.setText(txt3.getText()+"\tTotal: "+ (doblePareja+dobleParejaMesa)+"\n");
                txt3.setText(txt3.getText()+"Trios:\n");
                txt3.setText(txt3.getText()+"\tEn juego simple: "+ trio+"\n");
                txt3.setText(txt3.getText()+"\tEn mesa: "+ trioMesa+"\n");
                txt3.setText(txt3.getText()+"\tTotal: "+ (trio+trioMesa)+"\n");
                txt3.setText(txt3.getText()+"Color:\n");
                txt3.setText(txt3.getText()+"\tEn juego simple: "+ color+"\n");
                txt3.setText(txt3.getText()+"\tEn mesa: "+ colorMesa+"\n");
                txt3.setText(txt3.getText()+"\tTotal: "+ (color+colorMesa)+"\n");
                txt3.setText(txt3.getText()+"Full:\n");
                txt3.setText(txt3.getText()+"\tEn juego simple: "+ full+"\n");
                txt3.setText(txt3.getText()+"\tEn mesa: "+ fullMesa+"\n");
                txt3.setText(txt3.getText()+"\tTotal: "+ (full+fullMesa)+"\n");
                txt3.setText(txt3.getText()+"Poker:\n");
                txt3.setText(txt3.getText()+"\tEn juego simple: "+ poker+"\n");
                txt3.setText(txt3.getText()+"\tEn mesa: "+ pokerMesa+"\n");
                txt3.setText(txt3.getText()+"\tTotal: "+ (poker+pokerMesa)+"\n");
                txt3.setText(txt3.getText()+"Premios repartidos en total: "+(pareja+parejaMesa+doblePareja+dobleParejaMesa+trio+trioMesa+color+colorMesa+full+fullMesa+poker+pokerMesa));
                break;
        }
        
    }//GEN-LAST:event_L1ValueChanged

    private void L2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_L2ValueChanged
        int pareja = 0;
        int parejaMesa = 0;
        int doblePareja = 0;
        int dobleParejaMesa = 0;
        int trio = 0;
        int trioMesa = 0;
        int full = 0;
        int fullMesa = 0;
        int color = 0;
        int colorMesa = 0;
        int poker = 0;
        int pokerMesa = 0;
        Object [] datos = CasaDeApuestas.getRegistro().keySet().toArray();
        String [] claves = new String[datos.length];
        txt0.setText("");
        for (int x =0; x < datos.length; x++)
            claves[x] = datos [x].toString();
        for (String clave : claves) {
            pareja+=CasaDeApuestas.getregistrado(clave).premios.getPareja();
            parejaMesa+=CasaDeApuestas.getregistrado(clave).premios.getParejaMesa();
            doblePareja+=CasaDeApuestas.getregistrado(clave).premios.getDoblePareja();
            dobleParejaMesa+=CasaDeApuestas.getregistrado(clave).premios.getDobleParejaMesa();
            trio+=CasaDeApuestas.getregistrado(clave).premios.getTrio();
            trioMesa+=CasaDeApuestas.getregistrado(clave).premios.getTrioMesa();
            full+=CasaDeApuestas.getregistrado(clave).premios.getFull();
            fullMesa+=CasaDeApuestas.getregistrado(clave).premios.getFullMesa();
            color+=CasaDeApuestas.getregistrado(clave).premios.getColor();
            colorMesa+=CasaDeApuestas.getregistrado(clave).premios.getColorMesa();
            poker+=CasaDeApuestas.getregistrado(clave).premios.getPoker();
            pokerMesa+=CasaDeApuestas.getregistrado(clave).premios.getPokerMesa();
            switch(L2.getSelectedIndex())
            {
                case 0:
                    if((pareja+parejaMesa) > 0)
                    {
                        txt0.setText(clave+"\n");
                    }     
                    break;
                case 1:
                    if((doblePareja+dobleParejaMesa) > 0)
                    {
                        txt0.setText(clave+"\n");
                    } 
                    break;
                case 2:
                    if((trio+trioMesa) > 0)
                    {
                        txt0.setText(clave+"\n");
                    } 
                    break;
                case 4:
                    if((full+fullMesa) > 0)
                    {
                        txt0.setText(clave+"\n");
                    } 
                    break;
                case 3:
                    if((color+colorMesa) > 0)
                    {
                        txt0.setText(clave+"\n");
                    } 
                    break;
                case 5:
                    if((poker+pokerMesa) > 0)
                    {
                        txt0.setText(clave+"\n");
                    } 
                    break;
            }
            pareja = 0;
            parejaMesa = 0;
            doblePareja = 0;
            dobleParejaMesa = 0;
            trio = 0;
            trioMesa = 0;
            full = 0;
            fullMesa = 0;
            color = 0;
            colorMesa = 0;
            poker = 0;
            pokerMesa = 0;
        }
    }//GEN-LAST:event_L2ValueChanged

    private void L3ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_L3ValueChanged
        ArrayList <Premio> parejas = new ArrayList<>();
        ArrayList <Premio> doblesParejas = new ArrayList<>();
        ArrayList <Premio> trios = new ArrayList<>();
        ArrayList <Premio> fulls = new ArrayList<>();
        ArrayList <Premio> colores = new ArrayList<>();
        ArrayList <Premio> pokers = new ArrayList<>();
        txt4.setText("");
        for (int x=0; x<CasaDeApuestas.getregistrado(L3.getSelectedValue()).premios.getPremios().size();x++) 
        {
          switch(((Premio)CasaDeApuestas.getregistrado(L3.getSelectedValue()).premios.getPremios().get(x)).getTipo())
            {
                case 0:
                    parejas.add(((Premio)CasaDeApuestas.getregistrado(L3.getSelectedValue()).premios.getPremios().get(x)));
                    break;
                case 1:
                    doblesParejas.add(((Premio)CasaDeApuestas.getregistrado(L3.getSelectedValue()).premios.getPremios().get(x)));
                    break;
                case 2:
                    trios.add(((Premio)CasaDeApuestas.getregistrado(L3.getSelectedValue()).premios.getPremios().get(x)));
                    break;
                case 4:
                    fulls.add(((Premio)CasaDeApuestas.getregistrado(L3.getSelectedValue()).premios.getPremios().get(x))); 
                    break;
                case 3:
                    colores.add(((Premio)CasaDeApuestas.getregistrado(L3.getSelectedValue()).premios.getPremios().get(x))); 
                    break;
                case 5:
                    pokers.add(((Premio)CasaDeApuestas.getregistrado(L3.getSelectedValue()).premios.getPremios().get(x))); 
                    break;
            }  
        }
        txt4.setText(txt4.getText()+"Parejas:\n");
        parejas.forEach((pareja) -> {
            if(pareja.getEnMesa())
                txt4.setText(txt4.getText()+"\tEn mesa --> \t"+pareja.getPremio()+"$\n");
            else
                txt4.setText(txt4.getText()+"\tEn Juego simple --> \t"+pareja.getPremio()+"$\n");
        });
        txt4.setText(txt4.getText()+"DoblesParejas:\n");
        doblesParejas.forEach((doblePareja) -> {
            if(doblePareja.getEnMesa())
                txt4.setText(txt4.getText()+"\tEn mesa --> \t"+doblePareja.getPremio()+"$\n");
            else
                txt4.setText(txt4.getText()+"\tEn Juego simple --> \t"+doblePareja.getPremio()+"$\n");
        });
        txt4.setText(txt4.getText()+"Trios:\n");
        trios.forEach((trio) -> {
            if(trio.getEnMesa())
                txt4.setText(txt4.getText()+"\tEn mesa --> \t"+trio.getPremio()+"$\n");
            else
                txt4.setText(txt4.getText()+"\tEn Juego simple --> \t"+trio.getPremio()+"$\n");
        });
        txt4.setText(txt4.getText()+"Fulls:\n");
        txt4.setText(txt4.getText()+"Colores:\n");
        colores.forEach((color) -> {
            if(color.getEnMesa())
                txt4.setText(txt4.getText()+"\tEn mesa --> \t"+color.getPremio()+"$\n");
            else
                txt4.setText(txt4.getText()+"\tEn Juego simple --> \t"+color.getPremio()+"$\n");
        });
        fulls.forEach((full) -> {
            if(full.getEnMesa())
                txt4.setText(txt4.getText()+"\tEn mesa --> \t"+full.getPremio()+"$\n");
            else
                txt4.setText(txt4.getText()+"\tEn Juego simple --> \t"+full.getPremio()+"$\n");
        });
        txt4.setText(txt4.getText()+"Pokers:\n");
        pokers.forEach((poker) -> {
            if(poker.getEnMesa())
                txt4.setText(txt4.getText()+"\tEn mesa --> \t"+poker.getPremio()+"$\n");
            else
                txt4.setText(txt4.getText()+"\tEn Juego simple --> \t"+poker.getPremio()+"$\n");
        });
    }//GEN-LAST:event_L3ValueChanged

    private void L4ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_L4ValueChanged
        int pareja = 0;
        int parejaMesa = 0;
        int doblePareja = 0;
        int dobleParejaMesa = 0;
        int trio = 0;
        int trioMesa = 0;
        int full = 0;
        int fullMesa = 0;
        int color = 0;
        int colorMesa = 0;
        int poker = 0;
        int pokerMesa = 0;
        
        pareja+=CasaDeApuestas.getregistrado(L4.getSelectedValue()).premios.getPareja();
        parejaMesa+=CasaDeApuestas.getregistrado(L4.getSelectedValue()).premios.getParejaMesa();
        doblePareja+=CasaDeApuestas.getregistrado(L4.getSelectedValue()).premios.getDoblePareja();
        dobleParejaMesa+=CasaDeApuestas.getregistrado(L4.getSelectedValue()).premios.getDobleParejaMesa();
        trio+=CasaDeApuestas.getregistrado(L4.getSelectedValue()).premios.getTrio();
        trioMesa+=CasaDeApuestas.getregistrado(L4.getSelectedValue()).premios.getTrioMesa();
        full+=CasaDeApuestas.getregistrado(L4.getSelectedValue()).premios.getFull();
        fullMesa+=CasaDeApuestas.getregistrado(L4.getSelectedValue()).premios.getFullMesa();
        color+=CasaDeApuestas.getregistrado(L4.getSelectedValue()).premios.getColor();
        colorMesa+=CasaDeApuestas.getregistrado(L4.getSelectedValue()).premios.getColorMesa();
        poker+=CasaDeApuestas.getregistrado(L4.getSelectedValue()).premios.getPoker();
        pokerMesa+=CasaDeApuestas.getregistrado(L4.getSelectedValue()).premios.getPokerMesa();
        
        
        txt5.setText("Parejas:\n");
        txt5.setText(txt5.getText()+"\tEn juego simple: "+ pareja+"\n");
        txt5.setText(txt5.getText()+"\tEn mesa: "+ parejaMesa+"\n");
        txt5.setText(txt5.getText()+"\tTotal: "+ (pareja+parejaMesa)+"\n");
        txt5.setText(txt5.getText()+"DoblesParejas:\n");
        txt5.setText(txt5.getText()+"\tEn juego simple: "+ doblePareja+"\n");
        txt5.setText(txt5.getText()+"\tEn mesa: "+ dobleParejaMesa+"\n");
        txt5.setText(txt5.getText()+"\tTotal: "+ (doblePareja+dobleParejaMesa)+"\n");
        txt5.setText(txt5.getText()+"Trios:\n");
        txt5.setText(txt5.getText()+"\tEn juego simple: "+ trio+"\n");
        txt5.setText(txt5.getText()+"\tEn mesa: "+ trioMesa+"\n");
        txt5.setText(txt5.getText()+"\tTotal: "+ (trio+trioMesa)+"\n");
        txt5.setText(txt5.getText()+"Color:\n");
        txt5.setText(txt5.getText()+"\tEn juego simple: "+ color+"\n");
        txt5.setText(txt5.getText()+"\tEn mesa: "+ colorMesa+"\n");
        txt5.setText(txt5.getText()+"\tTotal: "+ (color+colorMesa)+"\n");
        txt5.setText(txt5.getText()+"Full:\n");
        txt5.setText(txt5.getText()+"\tEn juego simple: "+ full+"\n");
        txt5.setText(txt5.getText()+"\tEn mesa: "+ fullMesa+"\n");
        txt5.setText(txt5.getText()+"\tTotal: "+ (full+fullMesa)+"\n");
        txt5.setText(txt5.getText()+"Poker:\n");
        txt5.setText(txt5.getText()+"\tEn juego simple: "+ poker+"\n");
        txt5.setText(txt5.getText()+"\tEn mesa: "+ pokerMesa+"\n");
        txt5.setText(txt5.getText()+"\tTotal: "+ (poker+pokerMesa)+"\n");
        txt5.setText(txt5.getText()+"Premios repartidos en total: "+(pareja+parejaMesa+doblePareja+dobleParejaMesa+trio+trioMesa+color+colorMesa+full+fullMesa+poker+pokerMesa));

    }//GEN-LAST:event_L4ValueChanged

    private void L5ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_L5ValueChanged
        ArrayList <Premio> parejas = new ArrayList<>();
        ArrayList <Premio> doblesParejas = new ArrayList<>();
        ArrayList <Premio> trios = new ArrayList<>();
        ArrayList <Premio> fulls = new ArrayList<>();
        ArrayList <Premio> colores = new ArrayList<>();
        ArrayList <Premio> pokers = new ArrayList<>();
        txt6.setText("");
        for (int x=0; x<CasaDeApuestas.getregistrado(L5.getSelectedValue()).premios.getPremios().size();x++) 
        {
          switch(((Premio)CasaDeApuestas.getregistrado(L5.getSelectedValue()).premios.getPremios().get(x)).getTipo())
            {
                case 0:
                    parejas.add(((Premio)CasaDeApuestas.getregistrado(L5.getSelectedValue()).premios.getPremios().get(x)));
                    break;
                case 1:
                    doblesParejas.add(((Premio)CasaDeApuestas.getregistrado(L5.getSelectedValue()).premios.getPremios().get(x)));
                    break;
                case 2:
                    trios.add(((Premio)CasaDeApuestas.getregistrado(L5.getSelectedValue()).premios.getPremios().get(x)));
                    break;
                case 4:
                    fulls.add(((Premio)CasaDeApuestas.getregistrado(L5.getSelectedValue()).premios.getPremios().get(x))); 
                    break;
                case 3:
                    colores.add(((Premio)CasaDeApuestas.getregistrado(L5.getSelectedValue()).premios.getPremios().get(x))); 
                    break;
                case 5:
                    pokers.add(((Premio)CasaDeApuestas.getregistrado(L5.getSelectedValue()).premios.getPremios().get(x))); 
                    break;
            }  
        }
        
        int pareja = 0;
        double parejan = 0;
        int parejaMesa = 0;
        double parejaMesan = 0;
        int doblePareja = 0;
        double dobleParejan = 0;
        int dobleParejaMesa = 0;
        double dobleParejaMesan = 0;
        int trio = 0;
        double trion = 0;
        int trioMesa = 0;
        double trioMesan = 0;
        int full = 0;
        double fulln =0;
        int fullMesa = 0;
        double fullMesan = 0;
        int color = 0;
        double colorn = 0;
        int colorMesa = 0;
        double colorMesan = 0;
        int poker = 0;
        double pokern = 0;
        int pokerMesa = 0;
        double pokerMesan = 0;
        
        pareja+=CasaDeApuestas.getregistrado(L5.getSelectedValue()).premios.getPareja();
        parejaMesa+=CasaDeApuestas.getregistrado(L5.getSelectedValue()).premios.getParejaMesa();
        doblePareja+=CasaDeApuestas.getregistrado(L5.getSelectedValue()).premios.getDoblePareja();
        dobleParejaMesa+=CasaDeApuestas.getregistrado(L5.getSelectedValue()).premios.getDobleParejaMesa();
        trio+=CasaDeApuestas.getregistrado(L5.getSelectedValue()).premios.getTrio();
        trioMesa+=CasaDeApuestas.getregistrado(L5.getSelectedValue()).premios.getTrioMesa();
        full+=CasaDeApuestas.getregistrado(L5.getSelectedValue()).premios.getFull();
        fullMesa+=CasaDeApuestas.getregistrado(L5.getSelectedValue()).premios.getFullMesa();
        color+=CasaDeApuestas.getregistrado(L5.getSelectedValue()).premios.getColor();
        colorMesa+=CasaDeApuestas.getregistrado(L5.getSelectedValue()).premios.getColorMesa();
        poker+=CasaDeApuestas.getregistrado(L5.getSelectedValue()).premios.getPoker();
        pokerMesa+=CasaDeApuestas.getregistrado(L5.getSelectedValue()).premios.getPokerMesa();
        
        
        txt6.setText("Parejas:\n");
        txt6.setText(txt6.getText()+"\tEn juego simple: "+ pareja+"\n");
        for (int x=0; x < parejas.size(); x++)
        {
            if(!parejas.get(x).getEnMesa())
            {
                txt6.setText(txt6.getText()+"\t--> \t"+parejas.get(x).getPremio()+"\n");
                parejan += parejas.get(x).getPremio();
            }
        }
        txt6.setText(txt6.getText()+"\tsubtotal: "+parejan+"$\n");
        txt6.setText(txt6.getText()+"\tEn mesa: "+ parejaMesa+"\n");
        for (int x=0; x < parejas.size(); x++)
        {
            if(parejas.get(x).getEnMesa())
            {
                txt6.setText(txt6.getText()+"\t--> \t"+parejas.get(x).getPremio()+"\n");
                parejaMesan += parejas.get(x).getPremio();
            }
        }
        txt6.setText(txt6.getText()+"\tsubtotal: "+parejan+"$\n");
        txt6.setText(txt6.getText()+"\tTotal: "+ (pareja+parejaMesa)+"\t--> "+(parejan+parejaMesan)+"$\n");
        
        
        txt6.setText(txt6.getText()+"DoblesParejas:\n");
        txt6.setText(txt6.getText()+"\tEn juego simple: "+ doblePareja+"\n");
        for (int x=0; x < doblesParejas.size(); x++)
        {
            if(!doblesParejas.get(x).getEnMesa())
            {
                txt6.setText(txt6.getText()+"\t--> \t"+doblesParejas.get(x).getPremio()+"\n");
                dobleParejan += doblesParejas.get(x).getPremio();
            }
        }
        txt6.setText(txt6.getText()+"\tsubtotal: "+dobleParejan+"$\n");
        txt6.setText(txt6.getText()+"\tEn mesa: "+ dobleParejaMesa+"\n");
        for (int x=0; x < doblesParejas.size(); x++)
        {
            if(doblesParejas.get(x).getEnMesa())
            {
                txt6.setText(txt6.getText()+"\t--> \t"+doblesParejas.get(x).getPremio()+"\n");
                dobleParejaMesan += doblesParejas.get(x).getPremio();
            }
        }
        txt6.setText(txt6.getText()+"\tsubtotal: "+dobleParejaMesan+"$\n");
        txt6.setText(txt6.getText()+"\tTotal: "+ (doblePareja+dobleParejaMesa)+"\t--> "+(dobleParejan+dobleParejaMesan)+"$\n");
        
        
        txt6.setText(txt6.getText()+"Trios:\n");
        txt6.setText(txt6.getText()+"\tEn juego simple: "+ trio+"\n");
        for (int x=0; x < trios.size(); x++)
        {
            if(!trios.get(x).getEnMesa())
            {
                txt6.setText(txt6.getText()+"\t--> \t"+trios.get(x).getPremio()+"\n");
                trion += trios.get(x).getPremio();
            }
        }
        txt6.setText(txt6.getText()+"\tsubtotal: "+trion+"$\n");
        txt6.setText(txt6.getText()+"\tEn mesa: "+ trioMesa+"\n");
        for (int x=0; x < trios.size(); x++)
        {
            if(trios.get(x).getEnMesa())
            {
                txt6.setText(txt6.getText()+"\t--> \t"+trios.get(x).getPremio()+"\n");
                trioMesan += trios.get(x).getPremio();
            }
        }
        txt6.setText(txt6.getText()+"\tsubtotal: "+trioMesan+"$\n");
        txt6.setText(txt6.getText()+"\tTotal: "+ (trio+trioMesa)+"\t--> "+(trion+trioMesan)+"$\n");
        
        
        txt6.setText(txt6.getText()+"Color:\n");
        txt6.setText(txt6.getText()+"\tEn juego simple: "+ color+"\n");
        for (int x=0; x < colores.size(); x++)
        {
            if(!colores.get(x).getEnMesa())
            {
                txt6.setText(txt6.getText()+"\t--> \t"+colores.get(x).getPremio()+"\n");
                colorn += colores.get(x).getPremio();
            }
        }
        txt6.setText(txt6.getText()+"\tsubtotal: "+colorn+"$\n");
        txt6.setText(txt6.getText()+"\tEn mesa: "+ colorMesa+"\n");
        for (int x=0; x < colores.size(); x++)
        {
            if(colores.get(x).getEnMesa())
            {
                txt6.setText(txt6.getText()+"\t--> \t"+colores.get(x).getPremio()+"\n");
                colorMesan += colores.get(x).getPremio();
            }
        }
        txt6.setText(txt6.getText()+"\tsubtotal: "+colorMesan+"$\n");
        txt6.setText(txt6.getText()+"\tTotal: "+ (color+colorMesa)+"\t--> "+(colorn+colorMesan)+"$\n");
        
        
        txt6.setText(txt6.getText()+"Full:\n");
        txt6.setText(txt6.getText()+"\tEn juego simple: "+ full+"\n");
        for (int x=0; x < fulls.size(); x++)
        {
            if(!fulls.get(x).getEnMesa())
            {
                txt6.setText(txt6.getText()+"\t--> \t"+fulls.get(x).getPremio()+"\n");
                fulln += fulls.get(x).getPremio();
            }
        }
        txt6.setText(txt6.getText()+"\tsubtotal: "+fulln+"$\n");
        txt6.setText(txt6.getText()+"\tEn mesa: "+ fullMesa+"\n");
        for (int x=0; x < fulls.size(); x++)
        {
            if(fulls.get(x).getEnMesa())
            {
                txt6.setText(txt6.getText()+"\t--> \t"+fulls.get(x).getPremio()+"\n");
                fullMesan += fulls.get(x).getPremio();
            }
        }
        txt6.setText(txt6.getText()+"\tsubtotal: "+fullMesan+"$\n");
        txt6.setText(txt6.getText()+"\tTotal: "+ (full+fullMesa)+"\t--> "+(fulln+fullMesan)+"$\n");
        
        
        txt6.setText(txt6.getText()+"Poker:\n");
        txt6.setText(txt6.getText()+"\tEn juego simple: "+ poker+"\n");
        for (int x=0; x < pokers.size(); x++)
        {
            if(!pokers.get(x).getEnMesa())
            {
                txt6.setText(txt6.getText()+"\t--> \t"+pokers.get(x).getPremio()+"\n");
                pokern += pokers.get(x).getPremio();
            }
        }
        txt6.setText(txt6.getText()+"\tsubtotal: "+pokern+"$\n");
        txt6.setText(txt6.getText()+"\tEn mesa: "+ pokerMesa+"\n");
        for (int x=0; x < pokers.size(); x++)
        {
            if(pokers.get(x).getEnMesa())
            {
                txt6.setText(txt6.getText()+"\t--> \t"+pokers.get(x).getPremio()+"\n");
                pokerMesan += pokers.get(x).getPremio();
            }
        }
        txt6.setText(txt6.getText()+"\tsubtotal: "+pokerMesan+"$\n");
        txt6.setText(txt6.getText()+"\tTotal: "+ (poker+pokerMesa)+"\t--> "+(pokern+pokerMesan)+"$\n\n");
        txt6.setText(txt6.getText()+"Premios repartidos en total: "+(pareja+parejaMesa+doblePareja+dobleParejaMesa+trio+trioMesa+color+colorMesa+full+fullMesa+poker+pokerMesa)+"\t--> "+(parejan+parejaMesan+dobleParejan+dobleParejaMesan+trion+trioMesan+colorn+colorMesan+fulln+fullMesan+pokern+pokerMesan)+"$");
    }//GEN-LAST:event_L5ValueChanged

        private void actualizarList()
    {
        //Muestra los jugadores existentes
        Object [] datos = CasaDeApuestas.getRegistro().keySet().toArray();
        String [] claves = new String[datos.length];
        for (int x =0; x < datos.length; x++)
            claves[x] = datos [x].toString();
        L3.setListData(claves);
        L4.setListData(claves);
        L5.setListData(claves);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Ver().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> L1;
    private javax.swing.JList<String> L2;
    private javax.swing.JList<String> L3;
    private javax.swing.JList<String> L4;
    private javax.swing.JList<String> L5;
    private javax.swing.JList<String> List;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTab;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JTextArea txt0;
    private javax.swing.JTextArea txt1;
    private javax.swing.JTextArea txt2;
    private javax.swing.JTextArea txt3;
    private javax.swing.JTextArea txt4;
    private javax.swing.JTextArea txt5;
    private javax.swing.JTextArea txt6;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
